# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
no_package = True
skip_missing_interpreters = True
env_list = fmt, lint, static, unit, coverage-report
min_version = 4.0.0

[vars]
src_path = {tox_root}/src
tests_path = {tox_root}/tests
all_path = {[vars]src_path} {[vars]tests_path}

[testenv]
runner = uv-venv-lock-runner
set_env =
    PYTHONPATH = {tox_root}/lib:{[vars]src_path}
    PYTHONBREAKPOINT=pdb.set_trace
    PY_COLORS=1
pass_env =
    PYTHONPATH
    CHARM_BUILD_DIR
    MODEL_SETTINGS

[testenv:fmt]
description = Format the code
dependency_groups = fmt
commands =
    isort {[vars]src_path} {[vars]tests_path}
    black {[vars]src_path} {[vars]tests_path}

[testenv:lint]
description = Lint the code
dependency_groups = lint
commands =
    pydocstyle {[vars]src_path}
    codespell {tox_root} --skip {tox_root}/.git --skip {tox_root}/.tox \
      --skip {tox_root}/build --skip {tox_root}/lib --skip {tox_root}/.venv \
      --skip {tox_root}/.mypy_cache --skip {tox_root}/icon.svg --skip {tox_root}/uv.lock \
      --skip {tox_root}/documentation/.sphinx --skip {tox_root}/documentation/_build
    pflake8 {[vars]src_path} {[vars]tests_path}
    isort --check-only --diff {[vars]src_path} {[vars]tests_path}
    black --check --diff {[vars]src_path} {[vars]tests_path}
    mypy {[vars]all_path} --ignore-missing-imports --follow-imports=skip --install-types --non-interactive
    pylint {[vars]src_path} {[vars]tests_path} --disable=E0401,W1203,W0613,W0718,R0903,W1514,C0103,R0913,C0301,W0212,R0902,C0104,W0640,R0801,W0511,R0914,R0912,E1120


[testenv:unit]
description = Run unit tests
dependency_groups = test
commands =
    coverage run --source={[vars]src_path} \
                 -m pytest \
                 --tb native \
                 -v \
                 -s \
                 {posargs} \
                 {[vars]tests_path}/unit
    coverage report

[testenv:coverage-report]
description = Create test coverage report
dependency_groups = test
commands =
    coverage report

[testenv:static]
description = Run static analysis tests
dependency_groups = static
commands =
    bandit -c {tox_root}/pyproject.toml -r {[vars]src_path} {[vars]tests_path}

[testenv:integration]
description = Run integration tests
dependency_groups = integration
pass_env =
    CHARM_PATH
commands =
    pytest -v \
           -s \
           --tb native \
           --log-cli-level=INFO \
           {posargs} \
           {[vars]tests_path}/integration
