name: Integration tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      provider: "k8s"
      use-canonical-k8s: true
      channel: 1.32-classic/stable
      extra-arguments: |
        --kube-config=~/.kube/config
      modules: '["test_charm.py", "test_upgrade.py", "test_scaling.py"]'
      juju-channel: 3/stable
      self-hosted-runner: true
      self-hosted-runner-label: "self-hosted-linux-amd64-noble-xlarge"
      builder-runner-label: "self-hosted-linux-amd64-noble-xlarge"
      trivy-severity-config: CRITICAL
      rockcraft-enable-security-nesting: true
      tmate-debug: false
      with-uv: true
